In [ ]:
import pandas as pd
import requests

##Rankings

**Importing the Rankings for the end of the 2023-24 Season from the USAU website**

[usau rankings](https://play.usaultimate.org/teams/events/team_rankings/?RankSet=College-Men)

In [ ]:
url = "https://play.usaultimate.org/teams/events/team_rankings/?RankSet=College-Men"
team_rankings = pd.read_html("https://play.usaultimate.org/teams/events/team_rankings/?RankSet=College-Men", attrs = {'class': 'global_table'})

In [ ]:
team_rankings = pd.DataFrame(team_rankings[0])
team_rankings

,Rank,Team,Power Rating,Competition Level,Gender Division,Competition Division,College Region,College Conference,Wins,Losses
0,1,North Carolina,2124,College,Men,Division I,Atlantic Coast,Carolina DI,41,2
1,2,Massachusetts,2058,College,Men,Division I,New England,Greater New England DI,31,5
2,3,Cal Poly-SLO,1992,College,Men,Division I,Southwest,SoCal DI,39,7
3,4,Colorado,1969,College,Men,Division I,South Central,Rocky Mountain DI,29,6
4,5,Vermont,1940,College,Men,Division I,New England,Greater New England DI,26,11
5,6,Oregon,1923,College,Men,Division I,Northwest,Cascadia DI,36,11
6,7,Brown,1903,College,Men,Division I,New England,Greater New England DI,24,11
7,8,Pittsburgh,1898,College,Men,Division I,Ohio Valley,West Penn DI,27,8
8,9,California-Santa Cruz,1880,College,Men,Division I,Southwest,NorCal DI,33,10
9,10,Texas,1855,College,Men,Division I,South Central,South Texas DI,27,9
10,11,Carleton College,1817,College,Men,Division I,North Central,Northwoods DI,26,13
11,12,Minnesota,1797,College,Men,Division I,North Central,Northwoods DI,21,14
12,13,UCLA,1786,College,Men,Division I,Southwest,SoCal DI,24,9
13,14,Georgia,1777,College,Men,Division I,Southeast,Southern Appalachian DI,23,14
14,15,British Columbia,1762,College,Men,Division I,Northwest,Cascadia DI,19,9
15,16,California,1760,College,Men,Division I,Southwest,NorCal DI,31,15
16,17,Tufts,1719,College,Men,Division I,New England,Metro Boston DI,21,13
17,18,Washington,1711,College,Men,Division I,Northwest,Cascadia DI,25,20
18,19,Utah State,1651,College,Men,Division I,Northwest,Big Sky DI,24,17
19,20,Colorado College,1641,College,Men,Division III,South Central,Rocky Mountain DIII,24,5
20,Rows: 1 - 20 of 324« Previous 20 | 1 2 3 4 5 6...,Rows: 1 - 20 of 324« Previous 20 | 1 2 3 4 5 6...,Rows: 1 - 20 of 324« Previous 20 | 1 2 3 4 5 6...,Rows: 1 - 20 of 324« Previous 20 | 1 2 3 4 5 6...,Rows: 1 - 20 of 324« Previous 20 | 1 2 3 4 5 6...,Rows: 1 - 20 of 324« Previous 20 | 1 2 3 4 5 6...,Rows: 1 - 20 of 324« Previous 20 | 1 2 3 4 5 6...,Rows: 1 - 20 of 324« Previous 20 | 1 2 3 4 5 6...,Rows: 1 - 20 of 324« Previous 20 | 1 2 3 4 5 6...,Rows: 1 - 20 of 324« Previous 20 | 1 2 3 4 5 6...

In [ ]:
team_rankings.set_index("Rank", inplace=True)

Saving the team rankings to a csv in our shared drive for later use:

In [ ]:
team_rankings = team_rankings.iloc[:20:]
team_rankings
team_rankings.to_csv("team_rankings")

##Selenium

**In order to scrape all of the articles in question, we will need to use a webdriver**

**These are sources I used to figure out how to use Selenuim:**

Resources:

*   https://nariyoo.com/python-how-to-run-selenium-in-google-colab/
*   https://stackoverflow.com/questions/51046454how-can-we-use-selenium-webdriver-in-colab-research-google-com

*   https://www.selenium.dev/documentation/webdriver/

*   https://www.selenium.dev/documentation/webdriver/getting_started/first_script/
*   https://www.selenium.dev/documentation/webdriver/elements/interactions/

In [ ]:
pip install selenium

Collecting selenium
  Downloading selenium-4.15.2-py3-none-any.whl (10.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 27.8 MB/s eta 0:00:00
Requirement already satisfied: urllib3[socks]<3,>=1.26 in /usr/local/lib/python3.10/dist-packages (from selenium) (2.0.7)
Collecting trio~=0.17 (from selenium)
  Downloading trio-0.23.1-py3-none-any.whl (448 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 448.3/448.3 kB 18.5 MB/s eta 0:00:00
Collecting trio-websocket~=0.9 (from selenium)
  Downloading trio_websocket-0.11.1-py3-none-any.whl (17 kB)
Requirement already satisfied: certifi>=2021.10.8 in /usr/local/lib/python3.10/dist-packages (from selenium) (2023.7.22)
Requirement already satisfied: attrs>=20.1.0 in /usr/local/lib/python3.10/dist-packages (from trio~=0.17->selenium) (23.1.0)
Requirement already satisfied: sortedcontainers in /usr/local/lib/python3.10/dist-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in /usr/local/lib/python3.10/dist-packages (from trio~=0.17->selenium) (3.4)
Collecting outcome (from trio~=0.17->selenium)
  Downloading outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Requirement already satisfied: sniffio>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from trio~=0.17->selenium) (1.3.0)
Requirement already satisfied: exceptiongroup>=1.0.0rc9 in /usr/local/lib/python3.10/dist-packages (from trio~=0.17->selenium) (1.1.3)
Collecting wsproto>=0.14 (from trio-websocket~=0.9->selenium)
  Downloading wsproto-1.2.0-py3-none-any.whl (24 kB)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /usr/local/lib/python3.10/dist-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Collecting h11<1,>=0.9.0 (from wsproto>=0.14->trio-websocket~=0.9->selenium)
  Downloading h11-0.14.0-py3-none-any.whl (58 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 7.9 MB/s eta 0:00:00
Installing collected packages: outcome, h11, wsproto, trio, trio-websocket, selenium
Successfully installed h11-0.14.0 outcome-1.3.0.post0 selenium-4.15.2 trio-0.23.1 trio-websocket-0.11.1 wsproto-1.2.0

configuring a webdriver for selenium to use. This enables us to interact with a webpage we fetch

In [ ]:
%%shell
# Ubuntu no longer distributes chromium-browser outside of snap
#
# Proposed solution: https://askubuntu.com/questions/1204571/how-to-install-chromium-without-snap

# Add debian buster
cat > /etc/apt/sources.list.d/debian.list <<'EOF'
deb [arch=amd64 signed-by=/usr/share/keyrings/debian-buster.gpg] http://deb.debian.org/debian buster main
deb [arch=amd64 signed-by=/usr/share/keyrings/debian-buster-updates.gpg] http://deb.debian.org/debian buster-updates main
deb [arch=amd64 signed-by=/usr/share/keyrings/debian-security-buster.gpg] http://deb.debian.org/debian-security buster/updates main
EOF

# Add keys
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys DCC9EFBF77E11517
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 648ACFD622F3D138
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 112695A0E562B32A

apt-key export 77E11517 | gpg --dearmour -o /usr/share/keyrings/debian-buster.gpg
apt-key export 22F3D138 | gpg --dearmour -o /usr/share/keyrings/debian-buster-updates.gpg
apt-key export E562B32A | gpg --dearmour -o /usr/share/keyrings/debian-security-buster.gpg

# Prefer debian repo for chromium* packages only
# Note the double-blank lines between entries
cat > /etc/apt/preferences.d/chromium.pref << 'EOF'
Package: *
Pin: release a=eoan
Pin-Priority: 500


Package: *
Pin: origin "deb.debian.org"
Pin-Priority: 300


Package: chromium*
Pin: origin "deb.debian.org"
Pin-Priority: 700
EOF

# Install chromium and chromium-driver
apt-get update
apt-get install chromium chromium-driver

# Install selenium
pip install selenium

Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
Executing: /tmp/apt-key-gpghome.q2eFKkvs4o/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys DCC9EFBF77E11517
gpg: key DCC9EFBF77E11517: public key "Debian Stable Release Key (10/buster) <debian-release@lists.debian.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
Executing: /tmp/apt-key-gpghome.GHwwWXMgJC/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 648ACFD622F3D138
gpg: key DC30D7C23CBBABEE: public key "Debian Archive Automatic Signing Key (10/buster) <ftpmaster@debian.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
Executing: /tmp/apt-key-gpghome.i9pOwBY5xC/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 112695A0E562B32A
gpg: key 4DFAB270CAA96DFA: public key "Debian Security Archive Automatic Signing Key (10/buster) <ftpmaster@debian.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
Get:1 http://deb.debian.org/debian buster InRelease [122 kB]
Get:2 http://deb.debian.org/debian buster-updates InRelease [56.6 kB]
Get:3 http://deb.debian.org/debian-security buster/updates InRelease [34.8 kB]
Hit:4 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Get:5 http://deb.debian.org/debian buster/main amd64 Packages [10.7 MB]
Get:6 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Hit:7 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:8 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,626 B]
Get:9 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Get:10 http://deb.debian.org/debian buster-updates/main amd64 Packages [9,745 B]
Get:11 https://ppa.launchpadcontent.net/c2d4u.team/c2d4u4.0+/ubuntu jammy InRelease [18.1 kB]
Hit:12 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:13 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:14 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:15 http://deb.debian.org/debian-security buster/updates/main amd64 Packages [743 kB]
Hit:16 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Get:17 https://ppa.launchpadcontent.net/c2d4u.team/c2d4u4.0+/ubuntu jammy/main Sources [2,244 kB]
Get:18 https://ppa.launchpadcontent.net/c2d4u.team/c2d4u4.0+/ubuntu jammy/main amd64 Packages [1,152 kB]
Get:19 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,016 kB]
Get:20 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [1,520 kB]
Get:21 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [1,242 kB]
Get:22 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,284 kB]
Get:23 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [1,498 kB]
Fetched 21.9 MB in 3s (6,578 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  chromium-common chromium-sandbox libevent-2.1-6 libfontenc1 libgudev-1.0-0 libicu63
  libimobiledevice6 libjpeg62-turbo libjsoncpp1 libplist3 libre2-5 libu2f-udev libudev1
  libupower-glib3 libusbmuxd6 libvpx5 libwebp6 libxkbfile1 libxtst6 libxxf86dga1
  notification-daemon systemd-hwe-hwdb udev upower usbmuxd x11-utils
Suggested packages:
  chromium-l10n chromium-shell libusbmuxd-tools mesa-utils
The following NEW packages will be installed:
  chromium chromium-common chromium-driver chromium-sandbox libevent-2.1-6 libfontenc1
  libgudev-1.0-0 libicu63 libimobiledevice6 libjpeg62-turbo libjsoncpp1 libplist3 libre2-5
  libu2f-udev libupower-glib3 libusbmuxd6 libvpx5 libwebp6 libxkbfile1 libxtst6 libxxf86dga1
  notification-daemon systemd-hwe-hwdb udev upower usbmuxd x11-utils
The following packages will be upgraded:
  libudev1
1 upgraded, 27 newly installed, 0 to remove and 31 not upgraded.
Need to get 76.8 MB of archives.
After this operation, 267 MB of additional disk space will be used.
Get:1 http://deb.debian.org/debian buster/main amd64 libevent-2.1-6 amd64 2.1.8-stable-4 [177 kB]
Get:2 http://deb.debian.org/debian buster/main amd64 libicu63 amd64 63.1-6+deb10u3 [8,293 kB]
Get:3 http://deb.debian.org/debian buster/main amd64 libjpeg62-turbo amd64 1:1.5.2-2+deb10u1 [133 kB]
Get:4 http://deb.debian.org/debian buster/main amd64 libjsoncpp1 amd64 1.7.4-3 [75.6 kB]
Get:5 http://deb.debian.org/debian buster/main amd64 libre2-5 amd64 20190101+dfsg-2 [161 kB]
Get:6 http://deb.debian.org/debian-security buster/updates/main amd64 libvpx5 amd64 1.7.0-3+deb10u2 [800 kB]
Get:7 http://deb.debian.org/debian-security buster/updates/main amd64 libwebp6 amd64 0.6.1-2+deb10u3 [263 kB]
Get:8 http://deb.debian.org/debian buster/main amd64 chromium-common amd64 90.0.4430.212-1~deb10u1 [1,423 kB]
Get:9 http://deb.debian.org/debian buster/main amd64 chromium amd64 90.0.4430.212-1~deb10u1 [58.3 MB]
Get:10 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libudev1 amd64 249.11-0ubuntu3.11 [78.0 kB]
Get:11 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 udev amd64 249.11-0ubuntu3.11 [1,557 kB]
Get:12 http://deb.debian.org/debian buster/main amd64 chromium-driver amd64 90.0.4430.212-1~deb10u1 [4,703 kB]
Get:13 http://deb.debian.org/debian buster/main amd64 chromium-sandbox amd64 90.0.4430.212-1~deb10u1 [146 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy/main amd64 libfontenc1 amd64 1:1.1.4-1build3 [14.7 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxkbfile1 amd64 1:1.1.0-1build3 [71.8 kB]
Get:16 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxtst6 amd64 2:1.2.3-1build4 [13.4 kB]
Get:17 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxxf86dga1 amd64 2:1.1.5-0ubuntu3 [12.6 kB]
Get:18 http://archive.ubuntu.com/ubuntu jammy/main amd64 x11-utils amd64 7.7+5build2 [206 kB]
Get:19 http://archive.ubuntu.com/ubuntu jammy/main amd64 libgudev-1.0-0 amd64 1:237-2build1 [16.3 kB]
Get:20 http://archive.ubuntu.com/ubuntu jammy/main amd64 libplist3 amd64 2.2.0-6build2 [32.1 kB]
Get:21 http://archive.ubuntu.com/ubuntu jammy/main amd64 libusbmuxd6 amd64 2.0.2-3build2 [20.4 kB]
Get:22 http://archive.ubuntu.com/ubuntu jammy/main amd64 libimobiledevice6 amd64 1.3.0-6build3 [71.1 kB]
Get:23 http://archive.ubuntu.com/ubuntu jammy/main amd64 libu2f-udev all 1.1.10-3build2 [4,190 B]
Get:24 http://archive.ubuntu.com/ubuntu jammy/main amd64 libupower-glib3 amd64 0.99.17-1 [46.7 kB]
Get:25 http://archive.ubuntu.com/ubuntu jammy/universe amd64 notification-daemon amd64 3.20.0-4build1 [57.6 kB]
Get:26 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 systemd-hwe-hwdb all 249.11.3 [2,908 B]
Get:27 http://archive.ubuntu.com/ubuntu jammy/main amd64 upower amd64 0.99.17-1 [86.7 kB]
Get:28 http://archive.ubuntu.com/ubuntu jammy/main amd64 usbmuxd amd64 1.1.1-2build2 [42.8 kB]
Fetched 76.8 MB in 1s (75.2 MB/s)
(Reading database ... 120880 files and directories currently installed.)
Preparing to unpack .../libudev1_249.11-0ubuntu3.11_amd64.deb ...
Unpacking libudev1:amd64 (249.11-0ubuntu3.11) over (249.11-0ubuntu3.10) ...
Setting up libudev1:amd64 (249.11-0ubuntu3.11) ...
Selecting previously unselected package udev.
(Reading database ... 120880 files and directories currently installed.)
Preparing to unpack .../00-udev_249.11-0ubuntu3.11_amd64.deb ...
Unpacking udev (249.11-0ubuntu3.11) ...
Selecting previously unselected package libevent-2.1-6:amd64.
Preparing to unpack .../01-libevent-2.1-6_2.1.8-stable-4_amd64.deb ...
Unpacking libevent-2.1-6:amd64 (2.1.8-stable-4) ...
Selecting previously unselected package libicu63:amd64.
Preparing to unpack .../02-libicu63_63.1-6+deb10u3_amd64.deb ...
Unpacking libicu63:amd64 (63.1-6+deb10u3) ...
Selecting previously unselected package libjpeg62-turbo:amd64.
Preparing to unpack .../03-libjpeg62-turbo_1%3a1.5.2-2+deb10u1_amd64.deb ...
Unpacking libjpeg62-turbo:amd64 (1:1.5.2-2+deb10u1) ...
Selecting previously unselected package libjsoncpp1:amd64.
Preparing to unpack .../04-libjsoncpp1_1.7.4-3_amd64.deb ...
Unpacking libjsoncpp1:amd64 (1.7.4-3) ...
Selecting previously unselected package libre2-5:amd64.
Preparing to unpack .../05-libre2-5_20190101+dfsg-2_amd64.deb ...
Unpacking libre2-5:amd64 (20190101+dfsg-2) ...
Selecting previously unselected package libvpx5:amd64.
Preparing to unpack .../06-libvpx5_1.7.0-3+deb10u2_amd64.deb ...
Unpacking libvpx5:amd64 (1.7.0-3+deb10u2) ...
Selecting previously unselected package libwebp6:amd64.
Preparing to unpack .../07-libwebp6_0.6.1-2+deb10u3_amd64.deb ...
Unpacking libwebp6:amd64 (0.6.1-2+deb10u3) ...
Selecting previously unselected package libfontenc1:amd64.
Preparing to unpack .../08-libfontenc1_1%3a1.1.4-1build3_amd64.deb ...
Unpacking libfontenc1:amd64 (1:1.1.4-1build3) ...
Selecting previously unselected package libxkbfile1:amd64.
Preparing to unpack .../09-libxkbfile1_1%3a1.1.0-1build3_amd64.deb ...
Unpacking libxkbfile1:amd64 (1:1.1.0-1build3) ...
Selecting previously unselected package libxtst6:amd64.
Preparing to unpack .../10-libxtst6_2%3a1.2.3-1build4_amd64.deb ...
Unpacking libxtst6:amd64 (2:1.2.3-1build4) ...
Selecting previously unselected package libxxf86dga1:amd64.
Preparing to unpack .../11-libxxf86dga1_2%3a1.1.5-0ubuntu3_amd64.deb ...
Unpacking libxxf86dga1:amd64 (2:1.1.5-0ubuntu3) ...
Selecting previously unselected package x11-utils.
Preparing to unpack .../12-x11-utils_7.7+5build2_amd64.deb ...
Unpacking x11-utils (7.7+5build2) ...
Selecting previously unselected package chromium-common.
Preparing to unpack .../13-chromium-common_90.0.4430.212-1~deb10u1_amd64.deb ...
Unpacking chromium-common (90.0.4430.212-1~deb10u1) ...
Selecting previously unselected package chromium.
Preparing to unpack .../14-chromium_90.0.4430.212-1~deb10u1_amd64.deb ...
Unpacking chromium (90.0.4430.212-1~deb10u1) ...
Selecting previously unselected package chromium-driver.
Preparing to unpack .../15-chromium-driver_90.0.4430.212-1~deb10u1_amd64.deb ...
Unpacking chromium-driver (90.0.4430.212-1~deb10u1) ...
Selecting previously unselected package chromium-sandbox.
Preparing to unpack .../16-chromium-sandbox_90.0.4430.212-1~deb10u1_amd64.deb ...
Unpacking chromium-sandbox (90.0.4430.212-1~deb10u1) ...
Selecting previously unselected package libgudev-1.0-0:amd64.
Preparing to unpack .../17-libgudev-1.0-0_1%3a237-2build1_amd64.deb ...
Unpacking libgudev-1.0-0:amd64 (1:237-2build1) ...
Selecting previously unselected package libplist3:amd64.
Preparing to unpack .../18-libplist3_2.2.0-6build2_amd64.deb ...
Unpacking libplist3:amd64 (2.2.0-6build2) ...
Selecting previously unselected package libusbmuxd6:amd64.
Preparing to unpack .../19-libusbmuxd6_2.0.2-3build2_amd64.deb ...
Unpacking libusbmuxd6:amd64 (2.0.2-3build2) ...
Selecting previously unselected package libimobiledevice6:amd64.
Preparing to unpack .../20-libimobiledevice6_1.3.0-6build3_amd64.deb ...
Unpacking libimobiledevice6:amd64 (1.3.0-6build3) ...
Selecting previously unselected package libu2f-udev.
Preparing to unpack .../21-libu2f-udev_1.1.10-3build2_all.deb ...
Unpacking libu2f-udev (1.1.10-3build2) ...
Selecting previously unselected package libupower-glib3:amd64.
Preparing to unpack .../22-libupower-glib3_0.99.17-1_amd64.deb ...
Unpacking libupower-glib3:amd64 (0.99.17-1) ...
Selecting previously unselected package notification-daemon.
Preparing to unpack .../23-notification-daemon_3.20.0-4build1_amd64.deb ...
Unpacking notification-daemon (3.20.0-4build1) ...
Selecting previously unselected package systemd-hwe-hwdb.
Preparing to unpack .../24-systemd-hwe-hwdb_249.11.3_all.deb ...
Unpacking systemd-hwe-hwdb (249.11.3) ...
Selecting previously unselected package upower.
Preparing to unpack .../25-upower_0.99.17-1_amd64.deb ...
Unpacking upower (0.99.17-1) ...
Selecting previously unselected package usbmuxd.
Preparing to unpack .../26-usbmuxd_1.1.1-2build2_amd64.deb ...
Unpacking usbmuxd (1.1.1-2build2) ...
Setting up libplist3:amd64 (2.2.0-6build2) ...
Setting up libxtst6:amd64 (2:1.2.3-1build4) ...
Setting up libxxf86dga1:amd64 (2:1.1.5-0ubuntu3) ...
Setting up chromium-sandbox (90.0.4430.212-1~deb10u1) ...
Setting up libicu63:amd64 (63.1-6+deb10u3) ...
Setting up notification-daemon (3.20.0-4build1) ...
Setting up libfontenc1:amd64 (1:1.1.4-1build3) ...
Setting up libjpeg62-turbo:amd64 (1:1.5.2-2+deb10u1) ...
Setting up udev (249.11-0ubuntu3.11) ...
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
Setting up libwebp6:amd64 (0.6.1-2+deb10u3) ...
Setting up libevent-2.1-6:amd64 (2.1.8-stable-4) ...
Setting up systemd-hwe-hwdb (249.11.3) ...
Setting up libusbmuxd6:amd64 (2.0.2-3build2) ...
Setting up libupower-glib3:amd64 (0.99.17-1) ...
Setting up libre2-5:amd64 (20190101+dfsg-2) ...
Setting up libxkbfile1:amd64 (1:1.1.0-1build3) ...
Setting up libimobiledevice6:amd64 (1.3.0-6build3) ...
Setting up libgudev-1.0-0:amd64 (1:237-2build1) ...
Setting up libvpx5:amd64 (1.7.0-3+deb10u2) ...
Setting up libjsoncpp1:amd64 (1.7.4-3) ...
Setting up libu2f-udev (1.1.10-3build2) ...
Setting up upower (0.99.17-1) ...
Setting up usbmuxd (1.1.1-2build2) ...
Warning: The home dir /var/lib/usbmux you specified can't be accessed: No such file or directory
Adding system user `usbmux' (UID 104) ...
Adding new user `usbmux' (UID 104) with group `plugdev' ...
Not creating home directory `/var/lib/usbmux'.
Setting up x11-utils (7.7+5build2) ...
Setting up chromium-common (90.0.4430.212-1~deb10u1) ...
Setting up chromium (90.0.4430.212-1~deb10u1) ...
update-alternatives: using /usr/bin/chromium to provide /usr/bin/x-www-browser (x-www-browser) in auto mode
update-alternatives: using /usr/bin/chromium to provide /usr/bin/gnome-www-browser (gnome-www-browser) in auto mode
Setting up chromium-driver (90.0.4430.212-1~deb10u1) ...
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for dbus (1.12.20-2ubuntu4.1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for libc-bin (2.35-0ubuntu3.4) ...
/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

Requirement already satisfied: selenium in /usr/local/lib/python3.10/dist-packages (4.15.2)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in /usr/local/lib/python3.10/dist-packages (from selenium) (2.0.7)
Requirement already satisfied: trio~=0.17 in /usr/local/lib/python3.10/dist-packages (from selenium) (0.23.1)
Requirement already satisfied: trio-websocket~=0.9 in /usr/local/lib/python3.10/dist-packages (from selenium) (0.11.1)
Requirement already satisfied: certifi>=2021.10.8 in /usr/local/lib/python3.10/dist-packages (from selenium) (2023.7.22)
Requirement already satisfied: attrs>=20.1.0 in /usr/local/lib/python3.10/dist-packages (from trio~=0.17->selenium) (23.1.0)
Requirement already satisfied: sortedcontainers in /usr/local/lib/python3.10/dist-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in /usr/local/lib/python3.10/dist-packages (from trio~=0.17->selenium) (3.4)
Requirement already satisfied: outcome in /usr/local/lib/python3.10/dist-packages (from trio~=0.17->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from trio~=0.17->selenium) (1.3.0)
Requirement already satisfied: exceptiongroup>=1.0.0rc9 in /usr/local/lib/python3.10/dist-packages (from trio~=0.17->selenium) (1.1.3)
Requirement already satisfied: wsproto>=0.14 in /usr/local/lib/python3.10/dist-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /usr/local/lib/python3.10/dist-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: h11<1,>=0.9.0 in /usr/local/lib/python3.10/dist-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)




**Importing selenium and necessary functions.**

In [ ]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By

In [ ]:
!apt-get update
!apt-get install chromium chromium-driver

Hit:1 http://deb.debian.org/debian buster InRelease
Hit:2 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:3 http://deb.debian.org/debian buster-updates InRelease
Hit:4 http://deb.debian.org/debian-security buster/updates InRelease
Hit:5 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:6 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:7 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Hit:8 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:9 https://ppa.launchpadcontent.net/c2d4u.team/c2d4u4.0+/ubuntu jammy InRelease
Hit:10 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:11 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:12 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:13 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
chromium is already the newest version (90.0.4430.212-1~deb10u1).
chromium-driver is already the newest version (90.0.4430.212-1~deb10u1).
0 upgraded, 0 newly installed, 0 to remove and 31 not upgraded.

##Articles

**Scrape Ultiworld Articles about d1 college**

There are a pages on the ultiworld site containing links and graphics for each article related to the d1 college division. We want to navigate through each of these pages and find all of those links. Navigating through the pages and looking at the dates, IO was able to determine that the 19th page is as far is as relecant for our analysis.

[Here is the first page](https://ultiworld.com/division/usau-college-d-i-mens)

In [ ]:
article_links = []
first_page = "https://ultiworld.com/division/usau-college-d-i-mens"
response = requests.get(first_page)
soup = BeautifulSoup(response.content, "html.parser")

In [ ]:
articles = soup.find_all("h3", class_="snippet-excerpt__heading")
link = articles[0].find("a", href=True)['href']

In [ ]:
for article in articles:
  article_link = article.find("a", href=True)['href']
  article_links.append(article_link)
article_links

['https://ultiworld.com/2023/11/24/classic-city-classic-2023-tournament-recap/',
 'https://ultiworld.com/2023/11/17/classic-city-classic-2023-tournament-preview/',
 'https://ultiworld.com/2023/11/15/classic-city-classic-2023-streaming-schedule/',
 'https://ultiworld.com/2023/07/06/2023-mens-d-i-college-awards-snubs-superlatives/',
 'https://ultiworld.com/2023/06/27/ultiworlds-2023-d-i-college-awards-voting-breakdown/',
 'https://ultiworld.com/2023/06/23/2023-d-i-mens-coaches-of-the-year/',
 'https://ultiworld.com/2023/06/22/2023-d-i-mens-defensive-player-of-the-year/',
 'https://ultiworld.com/2023/06/21/2023-d-i-mens-offensive-player-of-the-year/',
 'https://ultiworld.com/2023/06/15/2023-d-i-mens-rookie-of-the-year/',
 'https://ultiworld.com/2023/06/14/2023-d-i-mens-breakout-player-of-the-year/']

In [ ]:
for idx in range(2, 19, 1):
  url = f"https://ultiworld.com/division/usau-college-d-i-mens/page/{idx}/"
  response = requests.get(url)
  soup = BeautifulSoup(response.content, "html.parser")
  articles = soup.find_all("h3", class_="snippet-excerpt__heading")
  for article in articles:
    article_link = article.find("a", href=True)['href']
    article_links.append(article_link)

In [ ]:
article_links

['https://ultiworld.com/2023/11/24/classic-city-classic-2023-tournament-recap/',
 'https://ultiworld.com/2023/11/17/classic-city-classic-2023-tournament-preview/',
 'https://ultiworld.com/2023/11/15/classic-city-classic-2023-streaming-schedule/',
 'https://ultiworld.com/2023/07/06/2023-mens-d-i-college-awards-snubs-superlatives/',
 'https://ultiworld.com/2023/06/27/ultiworlds-2023-d-i-college-awards-voting-breakdown/',
 'https://ultiworld.com/2023/06/23/2023-d-i-mens-coaches-of-the-year/',
 'https://ultiworld.com/2023/06/22/2023-d-i-mens-defensive-player-of-the-year/',
 'https://ultiworld.com/2023/06/21/2023-d-i-mens-offensive-player-of-the-year/',
 'https://ultiworld.com/2023/06/15/2023-d-i-mens-rookie-of-the-year/',
 'https://ultiworld.com/2023/06/14/2023-d-i-mens-breakout-player-of-the-year/',
 'https://ultiworld.com/2023/06/13/2023-d-i-mens-all-american-second-team/',
 'https://ultiworld.com/livewire/carnegie-mellons-wyatt-brooks-for-callahan-2023/',
 'https://ultiworld.com/2023/06/12/2023-d-i-mens-all-american-first-team/',
 'https://ultiworld.com/2023/06/08/2023-d-i-mens-player-of-the-year-pittsburghs-henry-ing/',
 'https://ultiworld.com/2023/06/07/college-championships-2023-d-i-and-d-iii-thegame-and-beat-charlie-challenge-results/',
 'https://ultiworld.com/2023/06/01/d-i-college-championships-2023-final-box-scores/',
 'https://ultiworld.com/livewire/wisconsins-nico-ranabhat-for-callahan-2023/',
 'https://ultiworld.com/livewire/case-westerns-james-kennelly-for-callahan-2023/',
 'https://ultiworld.com/livewire/csu-long-beachs-angus-fuori-for-callahan-2023/',
 'https://ultiworld.com/livewire/indianas-jeremy-keusch-for-callahan-2023/',
 'https://ultiworld.com/2023/05/31/best-tweets-of-the-2023-d-i-college-championships/',
 'https://ultiworld.com/2023/05/30/the-best-worst-and-most-interesting-jerseys-from-the-2023-d-i-college-championships/',
 'https://ultiworld.com/2023/05/30/2023-d-i-college-championships-darkside-make-it-three/',
 'https://ultiworld.com/2023/05/30/umass-and-cal-poly-slo-semifinal-shows-us-what-greatness-takes/',
 'https://ultiworld.com/2023/05/29/d-i-college-championships-2023-semifinal-box-scores/',
 'https://ultiworld.com/2023/05/29/unc-heats-up-melts-team-chill-d-i-college-championships-2023-semifinal-recap-mens/',
 'https://ultiworld.com/2023/05/29/d-i-college-championships-2023-final-preview-mens/',
 'https://ultiworld.com/2023/05/28/emorys-justin-burnett-wins-the-2023-callahan-award/',
 'https://ultiworld.com/2023/05/28/d-i-college-championships-2023-round-two-quarters-recap-mens/',
 'https://ultiworld.com/2023/05/28/d-i-college-championships-2023-round-one-quarters-recap-mens/',
 'https://ultiworld.com/2023/05/28/d-i-college-championships-2023-quarters-and-semis-live-coverage/',
 'https://ultiworld.com/2023/05/28/d-i-college-championships-2023-putting-prequarters-in-perspective-mens-day-two-recap/',
 'https://ultiworld.com/2023/05/28/mens-division-all-pool-lines-from-day-2-of-the-2023-d-i-college-championships/',
 'https://ultiworld.com/2023/05/28/2023-d-i-college-championships-2023-day-twos-3-2-1/',
 'https://ultiworld.com/2023/05/27/d-i-college-championships-2023-day-2-live-coverage/',
 'https://ultiworld.com/2023/05/27/d-i-college-championships-2023-day-one-awards-mens/',
 'https://ultiworld.com/2023/05/27/friday-surprises-at-the-2023-d-1-college-championships-mens/',
 'https://ultiworld.com/2023/05/27/d-i-college-championships-2023-pool-recap-mens/',
 'https://ultiworld.com/livewire/texas-zach-slayton-for-callahan-2023/',
 'https://ultiworld.com/2023/05/26/d-i-college-championships-2023-day-1-live-coverage/',
 'https://ultiworld.com/2023/05/26/the-top-25-d-i-mens-players-in-2023/',
 'https://ultiworld.com/2023/05/25/strength-and-understanding-zoodiscs-triumphant-return-to-nationals/',
 'https://ultiworld.com/2023/05/25/d-i-college-championships-2023-how-to-spot-a-cinderella/',
 'https://ultiworld.com/2023/05/25/faces-of-the-new-southwest/',
 'https://ultiworld.com/2023/05/25/d-i-college-championships-2023-pats-field-pass-watchability-rankings/',
 'https://ultiworld.com/livewire/cals-gavin-may-for-callahan-2023/',
 'https://ultiworld.com/2023/05/25/d-i-college-championships-2023-pool-previews-mens/',
 'https://ultiworld.com/2023/05/24/2023-d-i-college-championships-streaming-schedule-how-to-watch/',
 'https://ultiworld.com/2023/05/24/examining-d-i-mens-title-windows/',
 'https://ultiworld.com/2023/05/24/d-i-college-championships-2023-enter-to-win-thegame/',
 'https://ultiworld.com/2023/05/23/d-i-college-championships-2023-beat-charlie-challenge/',
 'https://ultiworld.com/2023/05/22/ultiworld-all-region-2023-d-i-first-team-mens-division/',
 'https://ultiworld.com/2023/05/20/2023-d-i-college-championships-pools-seeding-announced/',
 'https://ultiworld.com/livewire/virginias-stephen-dolan-for-callahan-2023/',
 'https://ultiworld.com/livewire/dartmouths-aaron-rosenthal-for-callahan-2023/',
 'https://ultiworld.com/livewire/temples-andrew-seibert-for-callahan-2023/',
 'https://ultiworld.com/livewire/auburns-david-perry-for-callahan-2023/',
 'https://ultiworld.com/livewire/tufts-zach-singer-for-callahan-2023/',
 'https://ultiworld.com/livewire/southern-californias-hari-sridhara-for-callahan-2023/',
 'https://ultiworld.com/livewire/uw-milwaukees-jackson-mccausland-for-callahan-2023/',
 'https://ultiworld.com/livewire/vanderbilts-david-atwood-for-callahan-2023/',
 'https://ultiworld.com/livewire/minnesotas-ian-mccosky-for-callahan-2023/',
 'https://ultiworld.com/livewire/georgias-adam-miller-for-callahan-2023/',
 'https://ultiworld.com/livewire/michigans-owen-oneil-for-callahan-2023/',
 'https://ultiworld.com/livewire/browns-leo-gordon-for-callahan-2023/',
 'https://ultiworld.com/livewire/northeasterns-thomas-griffin-for-callahan-2023/',
 'https://ultiworld.com/2023/05/12/universe-point-colorado-vs-oregon/',
 'https://ultiworld.com/livewire/penn-states-mike-dzelzgalvis-for-callahan-2023/',
 'https://ultiworld.com/livewire/northwesterns-sam-jonas-for-callahan-2023/',
 'https://ultiworld.com/livewire/central-floridas-reese-holiday-for-callahan-2023/',
 'https://ultiworld.com/livewire/nc-states-cooper-williams-for-callahan-2023/',
 'https://ultiworld.com/livewire/oregons-itay-chang-for-callahan-2023/',
 'https://ultiworld.com/livewire/unc-charlottes-ben-simmons-for-callahan-2023/',
 'https://ultiworld.com/2023/05/10/d-i-college-championships-2023-seeding-predictions/',
 'https://ultiworld.com/livewire/floridas-michael-arbutine-for-callahan-2023/',
 'https://ultiworld.com/livewire/pennsylvanias-carter-lynn-for-callahan-2023/',
 'https://ultiworld.com/livewire/virginia-techs-kiran-devine-for-callahan-2023/',
 'https://ultiworld.com/livewire/colorados-calvin-stoughton-for-callahan-2023/',
 'https://ultiworld.com/2023/05/10/deep-look-finalizing-the-nationals-field-d-i-regionals-recap/',
 'https://ultiworld.com/livewire/notre-dames-chris-walsh-for-callahan-2023/',
 'https://ultiworld.com/livewire/south-carolinas-bobby-gunshefski-for-callahan-2023/',
 'https://ultiworld.com/livewire/connecticuts-jasiu-kreciglowa-for-callahan-2023/',
 'https://ultiworld.com/livewire/suny-albanys-matt-obrien-for-callahan-2023/',
 'https://ultiworld.com/livewire/wash-us-ben-reimler-for-callahan-2023/',
 'https://ultiworld.com/livewire/mississippi-states-andrew-ohrberg-for-callahan-2023/',
 'https://ultiworld.com/livewire/colorado-states-jonathan-steiner-for-callahan-2023/',
 'https://ultiworld.com/livewire/suny-binghamtons-adam-cohen-for-callahan-2023/',
 'https://ultiworld.com/livewire/pittsburghs-henry-ing-for-callahan-2023/',
 'https://ultiworld.com/livewire/illinois-states-joe-cercello-for-callahan-2023/',
 'https://ultiworld.com/livewire/north-carolinas-andrew-li-for-callahan-2023/',
 'https://ultiworld.com/livewire/harvards-franky-fernandez-for-callahan-2023/',
 'https://ultiworld.com/livewire/lsus-mark-jeremiah-for-callahan-2023/',
 'https://ultiworld.com/livewire/cal-poly-slos-calvin-brown-for-callahan-2023/',
 'https://ultiworld.com/livewire/uclas-calvin-bird-for-callahan-2023/',
 'https://ultiworld.com/livewire/texas-states-jackson-potts-for-callahan-2023/',
 'https://ultiworld.com/2023/05/04/d-i-college-mens-regionals-2023-weekend-2-preview/',
 'https://ultiworld.com/livewire/iowas-cole-davis-for-callahan-2023/',
 'https://ultiworld.com/2023/05/04/2023-all-region-discussion-threads/',
 'https://ultiworld.com/livewire/johns-hopkins-quinn-hauck-for-callahan-2023/',
 'https://ultiworld.com/livewire/drexels-pat-oniate-for-callahan-2023/',
 'https://ultiworld.com/livewire/iowa-states-matt-johnson-for-callahan-2023/',
 'https://ultiworld.com/2023/05/04/deep-look-biggest-regionals-stories-and-pro-league-check-in/',
 'https://ultiworld.com/livewire/victorias-justin-pettenuzzo-for-callahan-2023/',
 'https://ultiworld.com/livewire/american-universitys-evan-malkin-for-callahan-2023/',
 'https://ultiworld.com/2023/05/01/college-update-biggest-regionals-storylines/',
 'https://ultiworld.com/2023/04/30/college-championships-2023-qualifying-thread/',
 'https://ultiworld.com/livewire/emorys-justin-burnett-for-callahan/',
 'https://ultiworld.com/2023/04/28/d-i-college-mens-regionals-2023-weekend-1-preview/',
 'https://ultiworld.com/2023/04/26/deep-look-regionals-picks-show-vs-double-overtime/',
 'https://ultiworld.com/2023/04/19/deep-look-audl-2023-preview-puls-amanda-dallas/',
 'https://ultiworld.com/2023/04/18/college-conference-championships-2023-roundup/',
 'https://ultiworld.com/2023/04/13/college-update-easterns-huck-finn-2/',
 'https://ultiworld.com/2023/04/13/universe-point-grand-canyon-vs-emory/',
 'https://ultiworld.com/2023/04/12/deep-look-d-i-bid-drama-small-ball/',
 'https://ultiworld.com/2023/04/11/universe-point-unc-wilmington-vs-case-western/',
 'https://ultiworld.com/2023/04/10/college-nationals-bids-change-hands-in-surprise-shifts-due-to-dropped-game-results/',
 'https://ultiworld.com/2023/04/07/easterns-2023-tournament-recap-mens/',
 'https://ultiworld.com/2023/04/06/huck-finn-2023-tournament-recap/',
 'https://ultiworld.com/2023/04/06/deep-look-easterns-recap-bid-picture-reactions/',
 'https://ultiworld.com/2023/04/04/universe-point-notre-dame-vs-virginia/',
 'https://ultiworld.com/2023/04/02/easterns-2023-day-one-headlines-bidwatch/',
 'https://ultiworld.com/2023/03/31/huck-finn-2023-tournament-preview/',
 'https://ultiworld.com/2023/03/31/universe-point-pittsburgh-vs-georgia/',
 'https://ultiworld.com/2023/03/31/d-i-college-bidwatch-3-30-23/',
 'https://ultiworld.com/2023/03/30/easterns-2023-tournament-preview-streaming-schedule-mens/',
 'https://ultiworld.com/2023/03/30/college-update-northwest-challenge-new-england-open-layout-pigout/',
 'https://ultiworld.com/2023/03/30/deep-look-northwest-challenge-recap-easterns-preview/',
 'https://ultiworld.com/2023/03/29/universe-point-pittsburgh-vs-byu/',
 'https://ultiworld.com/2023/03/24/universe-point-oregon-vs-uc-santa-cruz/',
 'https://ultiworld.com/2023/03/23/d-i-college-awards-2023-watchlist/',
 'https://ultiworld.com/2023/03/23/universe-point-oregon-vs-california/',
 'https://ultiworld.com/2023/03/22/deep-look-march-mailbag-centex-and-northwest-challenge/',
 'https://ultiworld.com/2023/03/20/college-update-centex-takes-center-stage/',
 'https://ultiworld.com/2023/03/19/centex-2023-day-one-recap-mens/',
 'https://ultiworld.com/2023/03/17/d-i-college-bidwatch-3-17-23/',
 'https://ultiworld.com/2023/03/17/universe-point-georgetown-vs-appalachian-state/',
 'https://ultiworld.com/2023/03/17/centex-2023-tournament-preview-and-streaming-schedule-mens/',
 'https://ultiworld.com/2023/03/16/deep-look-stanford-invite-womens-with-jenna-weiner-and-centex-preview/',
 'https://ultiworld.com/2023/03/15/universe-point-duke-vs-georgetown/',
 'https://ultiworld.com/2023/03/15/college-update-stanford-invite-tally-classic/',
 'https://ultiworld.com/2023/03/10/stanford-invite-2023-tournament-recap-mens/',
 'https://ultiworld.com/2023/03/10/deep-look-pul-rosters-wul-opener-and-big-college-weekends/',
 'https://ultiworld.com/2023/03/08/smoky-mountain-invite-tournament-recap-mens/',
 'https://ultiworld.com/2023/03/08/college-update-smoky-mountain-stanford-invite-fcs-d-iii-tune-up/',
 'https://ultiworld.com/2023/03/05/stanford-invite-trend-watch-day-1-recap/',
 'https://ultiworld.com/2023/03/05/smoky-mountain-invite-buy-hold-sell-day-1-recap/',
 'https://ultiworld.com/2023/03/03/stanford-invite-2023-tournament-preview-mens/',
 'https://ultiworld.com/2023/03/03/deep-look-college-midseason-solo-pod/',
 'https://ultiworld.com/2023/03/02/smoky-mountain-invite-2023-seven-burning-questions-tournament-preview-and-streaming-schedule/',
 'https://ultiworld.com/2023/03/02/college-update-commonwealth-cup-weekend-2-easterns-qualifier/',
 'https://ultiworld.com/2023/02/24/presidents-day-invite-2023-tournament-recap-mens/',
 'https://ultiworld.com/2023/02/23/deep-look-prez-day-recap-club-season-updates/',
 'https://ultiworld.com/2023/02/22/college-update-presidents-day/',
 'https://ultiworld.com/2023/02/20/presidents-day-invite-2023-re-ranking-the-field-day-2-mens-recap/',
 'https://ultiworld.com/2023/02/16/presidents-day-invite-2023-tournament-preview-streaming-schedule/',
 'https://ultiworld.com/2023/02/16/deep-look-offseason-player-movement-qctu-recap/',
 'https://ultiworld.com/2023/02/15/college-update-unc-sweeps-queen-city-tune-up/',
 'https://ultiworld.com/2023/02/14/queen-city-tune-up-2023-tournament-recap-mens/',
 'https://ultiworld.com/2023/02/10/florida-warm-up-mens-tournament-recap/',
 'https://ultiworld.com/2023/02/08/deep-look-2023-semi-pro-schedules-florida-warm-up-recap-and-qctu-preview/',
 'https://ultiworld.com/2023/02/08/queen-city-tune-up-2023-tournament-preview-streaming-schedule/',
 'https://ultiworld.com/2023/02/07/universe-point-texas-vs-unc-wilmington/',
 'https://ultiworld.com/2023/02/07/college-update-florida-warm-up-headlines-week-two-action/',
 'https://ultiworld.com/2023/02/05/florida-warm-up-2023-quarterfinals-graded-undersung-players-and-other-errata/',
 'https://ultiworld.com/2023/02/04/florida-warm-up-2023-friday-rants-raves/',
 'https://ultiworld.com/2023/02/03/d-i-mens-college-primer-2023/',
 'https://ultiworld.com/2023/02/02/huckin-eh-santa-barbara-baby-sbi-recap-and-uvic-interview/',
 'https://ultiworld.com/2023/02/02/universe-point-ohio-state-vs-georgia-tech/',
 'https://ultiworld.com/2023/02/02/santa-barbara-invite-2023-tournament-recap-mens/',
 'https://ultiworld.com/2023/02/01/deep-look-sbi-recap-florida-warm-up-preview/',
 'https://ultiworld.com/2023/02/01/carolina-kickoff-2023-mens-tournament-recap/',
 'https://ultiworld.com/2023/01/29/four-key-stories-from-day-one-at-sbi-2023-mens-division/',
 'https://ultiworld.com/2023/01/26/deep-look-d-i-college-preview-henry-ing/',
 'https://ultiworld.com/2023/01/26/santa-barbara-invite-2023-tournament-preview-streaming-schedule/',
 'https://ultiworld.com/2023/01/26/carolina-kickoff-2023-mens-tournament-preview-filming-schedule/',
 'https://ultiworld.com/2023/01/26/huckin-eh-bellingham-recap-santa-barbara-preview/',
 'https://ultiworld.com/2023/01/24/10-unranked-teams-to-watch/',
 'https://ultiworld.com/2023/01/20/2023-d-i-college-preseason-power-rankings-1-5/',
 'https://ultiworld.com/2023/01/19/2023-d-i-college-preseason-power-rankings-6-15/',
 'https://ultiworld.com/2023/01/18/2023-d-i-college-preseason-power-rankings-16-25/']

Now that we have a list of links to every article we want, we will scrape the text from the body of each article. First we define and configure an instance of a webdriver:

In [ ]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
options = webdriver.ChromeOptions()
options.add_argument("--verbose")
options.add_argument('--no-sandbox')
options.add_argument('--headless')
options.add_argument('--disable-gpu')
options.add_argument("--window-size=1920, 1200")
options.add_argument('--disable-dev-shm-usage')
options.add_argument("--dns-prefetch-disable")
driver = webdriver.Chrome(options=options)

Unfortunately, ulti world articles are held behind a pay wall for most of the season, and their site notoriously does not remember your login info. I bought a cheap access account for the project and used it to scrape the articles. Once we fetch and wait for a page to load, we check to see if the login prompt is preventing us from reading the article. If it is, we click on the login link, fill in our info, return to the article in question, and proceed to scrape the author, date, title, text. Repeat the process for a couple hundred links while taking a nap and it finishes running in just under 50 minutes!

In [ ]:
import time

texts = []
authors = []
dates = []
titles = []
count = 0

al = ['https://ultiworld.com/2023/01/10/bold-predictions-for-the-2023-college-season/']
def login(driver, link):
  driver.get(link)
  driver.find_element(By.LINK_TEXT, "Log in").click()
  driver.refresh()
  time.sleep(2)
  user_input = driver.find_element(By.ID, "user_login")
  user_input.send_keys("36triangles")
  pass_input = driver.find_element(By.ID, "user_pass")
  pass_input.send_keys("data301!")
  driver.find_element(By.ID, "wp-submit").click()

login(driver, article_links[0])
for link in article_links[1::]:
  try:
    login(driver, link)
  except:
    print("already loged in")
  driver.get(link)
  time.sleep(2)

  try:
    text = driver.find_element(By.XPATH, "/html/body/main/div[1]/div[2]").text
  except:
    text = 'None'

  try:
    author = driver.find_element(By.XPATH, "/html/body/main/div[1]/div[3]/ol/li/h5").text
  except:
    author = 'None'

  try:
    date = driver.find_element(By.XPATH, "/html/body/main/div[1]/div[2]/h6").text
  except:
    date = 'None'

  try:
    title = driver.find_element(By.XPATH, "/html/body/main/div[1]/div[1]/h1").text
  except:
    title = "None"

  texts.append(text)
  authors.append(author)
  dates.append(date)
  titles.append(title)

Finally, we get to put all the articles and their attributes into a dataframe, clean it, and save it for later use:

In [ ]:
df_articles = pd.DataFrame()
df_articles["author"] = authors
df_articles["text"] = texts
df_articles["date"] = dates
df_articles["title"] = titles
df_articles

,author,text,date,title
0,EDWARD STEPHENS,The college preseason pillar is back!\nNOVEMBE...,"NOVEMBER 17, 2023 BY EDWARD STEPHENS IN PREVIE...",Classic City Classic 2023: Tournament Preview
1,AIDAN SHAPIRO-LEIGHTON,The competitive college fall is here!\nNOVEMBE...,"NOVEMBER 15, 2023 BY AIDAN SHAPIRO-LEIGHTON IN...",Classic City Classic 2023: Streaming Schedule
2,ULTIWORLD,Our reporters celebrate some of their favorite...,"JULY 6, 2023 BY ULTIWORLD IN AWARDS WITH 0 COM...",2023 Men’s D-I College Awards: Snubs & Superla...
3,ULTIWORLD,See all of the vote-getters for every 2023 D-I...,"JUNE 27, 2023 BY ULTIWORLD IN AWARDS WITH 0 CO...",Ultiworld’s 2023 D-I College Awards Voting Bre...
4,JAKE THORNE,Celebrating the best off-field leaders of the ...,"JUNE 23, 2023 BY JAKE THORNE, ALEX RUBIN AND P...",2023 D-I Men’s Coaches of the Year
...,...,...,...,...
174,THEO WAN,The USA College Season is Officially here!\nJA...,"JANUARY 26, 2023 BY THEO WAN AND DANIE PROBY I...",Huckin’ Eh: Bellingham Recap & Santa Barbara P...
175,KEITH RAYNOR,Five teams from each division with all the goo...,"JANUARY 24, 2023 BY KEITH RAYNOR IN RANKINGS W...",10 Unranked Teams To Watch
176,EDWARD STEPHENS,We preview teams #1-5 in our Power Rankings he...,"JANUARY 20, 2023 BY EDWARD STEPHENS, PATRICK S...",2023 D-I College Preseason Power Rankings: #1-5
177,EDWARD STEPHENS,We preview teams #6-15 in our Power Rankings h...,"JANUARY 19, 2023 BY EDWARD STEPHENS, PATRICK S...",2023 D-I College Preseason Power Rankings: #6-15
178,EDWARD STEPHENS,We preview teams #16-25 in our Power Rankings ...,"JANUARY 18, 2023 BY EDWARD STEPHENS, PATRICK S...",2023 D-I College Preseason Power Rankings: #16-25

In [ ]:
df_articles.date.value_counts()
def clean_date(x):
  str_list = x.split("BY")
  return str_list[0]
df_articles["date"] = df_articles["date"].map(clean_date)

In [ ]:
df_articles["date"]
df_articles.to_csv("articles", sep=',', index=False, encoding='utf-8')

In [ ]:
potato = pd.read_csv("articles")



##Data Description

**Data we have collected**

So far, we have scraped and cleaned the Cal Poly 2023 men's frisbee roster, a table containing information on every team in the men's d1 college division. Each table's variables are team ranking, power rating, region, name, and record for the 2023 season. We have also scraped a list of news article links from Ultiworld, a site that reports on college frisbee. Each link represents an article written by Ultiworld about the men's d1 college division in the 2023 season, and each individual article is our unit of measurement.

**Data we still have to collect**

Although we have Cal Poly's roster for the 2023 season, we still have to scrape the rosters of all the other teams. These rosters contain player's first and last names. We intend to get the rosters from the United States Ultimate website listed above. To access the page, the link requires an additional link click, so we are working on getting that. Also, we still have to loop through the ultiworld links and scrape the text from each article. From each article, we will be pulling the total word count, author, and record the number of times each college frisbee team is mentioned. To be mentioned, we are looking for the team name, players' name, or school name. This way, we can compare the number of times each team is mentioned, and see if Cal Poly's Slocore is mentiioned at a different proportion than other schools.